### PR TITLE
fix use TemplateModel only in sendEmailWithTemplate

### LINKED ISSUE #7: forgot-password not working
I guess we both never spotted this:

```
debug POST /admin/forgot-password (7 ms) 204
error ApiInputError: A 'TemplateModel' may not be specified when sending through the '/email' endpoint. Please use the '/email/withTemplate' endpoint instead.
```

Will do some research a.s.a.p.

### PR DESCRIPTION
**Pull request by laurenskling**
fixes https://github.com/ijsto/strapi-provider-email-postmark/issues/7

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -46,20 +46,22 @@ module.exports = {
...
+            msg.TemplateModel = {
+              ...defaultVariables,
+              ...variables,
+            }
           }
 
-          client[method](removeUndefined(msg), function (err) {
+          client[method](removeUndefined({
+            ...msg,
+            ...rest,
```
Comment (laurenskling) [inline lib/index.js:63]: I moved this here, since in theory you could still override the `TemplateModel` in the send options

Comment (ScottAgirs) [reply lib/index.js:63]: Yeah, I think that makes sense, thanks for the note 🙌🏼

**Review by ScottAgirs — APPROVED** [review]
LGTM, thanks 🚀
